In [39]:
import pandas as pd
import numpy as np
import sklearn.preprocessing as Preprocessing
from sklearn.linear_model import LogisticRegression as lg

In [40]:
data = pd.read_pickle('features_MNLogit_Sample.csv')

In [41]:
data.shape

(10000, 2004)

In [42]:
data.head()

,user,sex,age,country,000d90ec-d64c-48a1-b775-e726fd240e9f,000fc734-b7e1-4a01-92d1-f544261b43f5,0019749d-ee29-4a5f-ab17-6bfa11deb969,0039c7ae-e1a7-4a7d-9b49-0cbc716821a6,004e5eed-e267-46ea-b504-54526f1f377d,00565b31-14a3-4913-bd22-385eb40dd13c,...,ff6e677f-91dd-4986-a174-8db0474b1799,ff7f80cd-05c2-4068-a00e-fbfbd453d049,ff865aa0-4603-4f79-ae8b-8735332e2cfa,ff95eb47-41c4-4f7f-a104-cdc30f02e872,ff9deaae-da4f-42b7-a19e-36fedd3fc706,ffb18e19-64a4-4a65-b4ce-979e00c3c69d,ffb2d3e3-a4cc-48cf-8fb0-f2f846e9d7b9,ffb390b8-8df4-4b72-97d1-7b2fc008a452,ffe16bba-4d84-409b-8f22-5242c60b930f,ffe9ec08-6b6b-4993-9394-e280b429dbfd
0,fa40b43298ba3f8aa52e8e8863faf2e2171e0b5d,f,25.0,Sweden,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5909125332c108365a26ccf0ee62636eee08215c,m,29.0,Iceland,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,d1867cbda35e0d48e9a8390d9f5e079c9d99ea96,m,30.0,United States,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,63268cce0d68127729890c1691f62d5be5abd87c,m,21.0,Germany,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,02871cd952d607ba69b64e2e107773012c708113,m,24.0,Netherlands,0.0,0.0,0.0,94.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
new_feature = data[['sex','country']]

# Encode categorical variables using sklearn's one-hot encoder
def encode_categorical(array):
    if not array.dtype == np.dtype('float64'):
        return Preprocessing.LabelEncoder().fit_transform(array) 
    else:
        return array
    
# Categorical columns for use in one-hot encoder
categorical = (new_feature.dtypes.values != np.dtype('float64'))

# Encode all labels
new_feature = new_feature.apply(encode_categorical)

# Get numpy array from data
x = new_feature.as_matrix()

# Apply one hot endcoing
encoder = Preprocessing.OneHotEncoder(categorical_features=categorical, sparse=False)  # Last value in mask is y
x = encoder.fit_transform(x)

In [45]:
np.unique(data.country)
x.shape

(10000, 983)

In [48]:
Y = data.iloc[:,4:]

In [51]:
Y.shape

(10000, 2000)

In [53]:
P = np.zeros([10000, 2000])

In [55]:
multi = lg(multi_class='multinomial', solver ='newton-cg')

In [56]:
multi.fit(x, P)

ValueError: bad input shape (10000, 2000)

In [60]:
#data.iloc[:,4:].median(axis=0)
data['new'] = np.zeros(10000)

In [67]:
for i in range(10000):
    data.set_value(i, 'new', data.iloc[i, 4:][data.iloc[i, 4:]>0].median())

In [65]:
#data.iloc[1,4:][data.iloc[1,4:]>0].median()

368.5

In [68]:
data.head()

,user,sex,age,country,000d90ec-d64c-48a1-b775-e726fd240e9f,000fc734-b7e1-4a01-92d1-f544261b43f5,0019749d-ee29-4a5f-ab17-6bfa11deb969,0039c7ae-e1a7-4a7d-9b49-0cbc716821a6,004e5eed-e267-46ea-b504-54526f1f377d,00565b31-14a3-4913-bd22-385eb40dd13c,...,ff7f80cd-05c2-4068-a00e-fbfbd453d049,ff865aa0-4603-4f79-ae8b-8735332e2cfa,ff95eb47-41c4-4f7f-a104-cdc30f02e872,ff9deaae-da4f-42b7-a19e-36fedd3fc706,ffb18e19-64a4-4a65-b4ce-979e00c3c69d,ffb2d3e3-a4cc-48cf-8fb0-f2f846e9d7b9,ffb390b8-8df4-4b72-97d1-7b2fc008a452,ffe16bba-4d84-409b-8f22-5242c60b930f,ffe9ec08-6b6b-4993-9394-e280b429dbfd,new
0,fa40b43298ba3f8aa52e8e8863faf2e2171e0b5d,f,25.0,Sweden,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0
1,5909125332c108365a26ccf0ee62636eee08215c,m,29.0,Iceland,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,368.5
2,d1867cbda35e0d48e9a8390d9f5e079c9d99ea96,m,30.0,United States,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.5
3,63268cce0d68127729890c1691f62d5be5abd87c,m,21.0,Germany,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2841.0
4,02871cd952d607ba69b64e2e107773012c708113,m,24.0,Netherlands,0.0,0.0,0.0,94.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,161.5

In [69]:
data.to_csv("samples1.csv")

In [23]:
data.head()

,sex,age,country,000d90ec-d64c-48a1-b775-e726fd240e9f,000fc734-b7e1-4a01-92d1-f544261b43f5,0019749d-ee29-4a5f-ab17-6bfa11deb969,0039c7ae-e1a7-4a7d-9b49-0cbc716821a6,004e5eed-e267-46ea-b504-54526f1f377d,00565b31-14a3-4913-bd22-385eb40dd13c,00a9f935-ba93-4fc8-a33a-993abe9c936b,...,ff6e677f-91dd-4986-a174-8db0474b1799,ff7f80cd-05c2-4068-a00e-fbfbd453d049,ff865aa0-4603-4f79-ae8b-8735332e2cfa,ff95eb47-41c4-4f7f-a104-cdc30f02e872,ff9deaae-da4f-42b7-a19e-36fedd3fc706,ffb18e19-64a4-4a65-b4ce-979e00c3c69d,ffb2d3e3-a4cc-48cf-8fb0-f2f846e9d7b9,ffb390b8-8df4-4b72-97d1-7b2fc008a452,ffe16bba-4d84-409b-8f22-5242c60b930f,ffe9ec08-6b6b-4993-9394-e280b429dbfd
0,f,25.0,Sweden,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,m,29.0,Iceland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,m,30.0,United States,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,m,21.0,Germany,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,m,24.0,Netherlands,0.0,0.0,0.0,94.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
import math

In [72]:
#calculate MAE score
def MAE_score(y_pred, y_test):
    return abs(np.array(y_pred)-np.array(y_test)).sum()/len(y_pred)

In [86]:
#a['x'] is nan 
a['x'][np.isnan(a['x'])] = 150
a.set_value(a.iloc[:, 1][np.isnan(a['x'])], 'x', 150)

/Users/ruizhao/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

      Unnamed: 0           x
0              1  148.872435
1              2  148.618241
2              3  220.704469
3              4  161.341963
4              5  173.858256
5              6  221.787420
6              7    0.000000
7              8    0.000000
8              9    0.000000
9             10  151.445864
10            11  122.980862
11            12  161.208812
12            13  160.947578
13            14  145.017376
14            15  210.460895
15            16  160.063733
16            17    0.000000
17            18  221.787420
18            19  223.147051
19            20    0.000000
20            21    0.000000
21            22  173.559042
22            23  219.492469
23            24  177.765006
24            25  150.602420
25            26  133.031931
26            27  136.970993
27            28  163.324518
28            29  221.923162
29            30  168.465724
...          ...         ...
9970        9971    0.000000
9971        9972  157.670952
9972        9973  157.767453
9973        9974  132.893226
9974        9975  221.516185
9975        9976    0.000000
9976        9977    0.000000
9977        9978  192.401560
9978        9979  168.465724
9979        9980  140.684506
9980        9981  161.440710
9981        9982  174.071137
9982        9983  267.958008
9983        9984  190.008273
9984        9985  141.461342
9985        9986    0.000000
9986        9987  168.568831
9987        9988  172.605941
9988        9989  159.582472
9989        9990  183.299391
9990        9991  167.951134
9991        9992  107.000000
9992        9993  221.380692
9993        9994  219.492469
9994        9995  162.296810
9995        9996  145.725725
9996        9997  224.060071
9997        9998  173.327194
9998        9999  167.233346
9999       10000  126.489606

[10000 rows x 2 columns]

In [76]:
a = pd.read_csv("result-samples1.csv")

In [88]:
MAE_score(a['x'], data['new'])

133.13023268167413

#########

In [113]:
alluser = pd.read_csv("user_count.csv")

In [114]:
alluser.head()

,Unnamed: 0,user,sex,age,country,plays
0,0,fa40b43298ba3f8aa52e8e8863faf2e2171e0b5d,f,25.0,Sweden,63.0
1,1,5909125332c108365a26ccf0ee62636eee08215c,m,29.0,Iceland,376.0
2,2,d1867cbda35e0d48e9a8390d9f5e079c9d99ea96,m,30.0,United States,20.5
3,3,63268cce0d68127729890c1691f62d5be5abd87c,m,21.0,Germany,2841.0
4,4,02871cd952d607ba69b64e2e107773012c708113,m,24.0,Netherlands,161.5

In [115]:
(np.isnan(alluser['age'])== True).count

<bound method Series.count of 0         False
1         False
2         False
3         False
4         False
5         False
6          True
7          True
8          True
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16         True
17        False
18        False
19         True
20         True
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
233256    False
233257    False
233258    False
233259    False
233260    False
233261    False
233262    False
233263    False
233264    False
233265    False
233266    False
233267    False
233268    False
233269    False
233270    False
233271    False
233272    False
233273    False
233274    False
233275     True
233276    False
233277    False
233278    False
233279    False
233280    False
233281    False
233282    False
233283    False
233284    False
233285    False
Name: age, dtype: bool>

In [116]:
alluser.shape

(233286, 6)

In [117]:
age_mean = np.mean(alluser[np.isnan(alluser['age'])!= True]['age'])

In [118]:
age_mean

24.517400394812253

In [124]:
# for i in range(len(alluser)):
#     alluser.set_value(i, 'age', alluser['age'].fillna(age_mean)[i])

In [125]:
alluser['age'].fillna(age_mean)

0         25.0000
1         29.0000
2         30.0000
3         21.0000
4         24.0000
5         22.0000
6         24.5174
7         24.5174
8         24.5174
9         16.0000
10        44.0000
11        17.0000
12        25.0000
13        24.0000
14        22.0000
15        34.0000
16        24.5174
17        22.0000
18        22.0000
19        24.5174
20        24.5174
21        28.0000
22        39.0000
23        19.0000
24        24.0000
25        26.0000
26        19.0000
27        19.0000
28        21.0000
29        21.0000
           ...
233256    29.0000
233257    21.0000
233258    36.0000
233259    24.0000
233260    21.0000
233261    23.0000
233262    18.0000
233263    29.0000
233264    24.0000
233265    23.0000
233266    29.0000
233267    16.0000
233268    17.0000
233269    35.0000
233270    18.0000
233271    20.0000
233272    18.0000
233273    30.0000
233274    44.0000
233275    24.5174
233276    22.0000
233277    24.0000
233278    18.0000
233279    31.0000
233280    26.0000
233281    26.0000
233282    19.0000
233283    22.0000
233284    17.0000
233285    21.0000
Name: age, dtype: float64

In [126]:
alluser['newage'] =  alluser['age'].fillna(age_mean)

In [129]:
alluser['newsex'] =  alluser['sex'].fillna('f')

In [130]:
alluser

,Unnamed: 0,user,sex,age,country,plays,newage,newsex
0,0,fa40b43298ba3f8aa52e8e8863faf2e2171e0b5d,f,25.0000,Sweden,63.0,25.0000,f
1,1,5909125332c108365a26ccf0ee62636eee08215c,m,29.0000,Iceland,376.0,29.0000,m
2,2,d1867cbda35e0d48e9a8390d9f5e079c9d99ea96,m,30.0000,United States,20.5,30.0000,m
3,3,63268cce0d68127729890c1691f62d5be5abd87c,m,21.0000,Germany,2841.0,21.0000,m
4,4,02871cd952d607ba69b64e2e107773012c708113,m,24.0000,Netherlands,161.5,24.0000,m
5,5,0938eb3d1b449b480c4e2431c457f6ead7063a34,m,22.0000,United States,420.5,22.0000,m
6,6,e4c6b36e65db3d48474dd538fe74d2dbb5a2e79e,f,24.5174,United States,53.0,24.5174,f
7,7,b97479f9a563a5c43b423a976f51fd509e1ec5ba,f,24.5174,Poland,50.0,24.5174,f
8,8,3bb020df0ff376dfdded4d5e63e2d35a50b3c535,m,24.5174,United States,172.5,24.5174,m
9,9,f3fb86c0f024f640cae3fb479f3a27e0dd499891,NaN,16.0000,Ukraine,5.0,16.0000,f
10,10,ed3f59e940c08a34434ecb999cbb184bd4f3fe60,m,44.0000,Italy,210.0,44.0000,m
11,11,84b0024025a9b85ac11250419f2223cd36171be7,m,17.0000,Russian Federation,366.5,17.0000,m
12,12,6af1f8a3748f2905913f1ef698d319fb39251200,m,25.0000,Germany,85.5,25.0000,m
13,13,6f6061ee85758d2f28dc813793d10fc28cc7ab3e,m,24.0000,Austria,63.0,24.0000,m
14,14,beb313d271e1b0aee0d43e2598ad606b97246151,f,22.0000,Australia,24.5,22.0000,f
15,15,11c25963a9ae5012163b415852655ff5443c977f,m,34.0000,Germany,23.0,34.0000,m
16,16,7970e94ae2fcbcac725c395dfdbaf4cfb7e44e1e,m,24.5174,United States,102.0,24.5174,m
17,17,b9a661b805db8a7dcfec13e4800717c43ae89ae5,m,22.0000,United States,35.5,22.0000,m
18,18,80460a9d1c784e730a1fe65e16ce5c7945330e6d,m,22.0000,Canada,227.5,22.0000,m
19,19,e5e50794b2db0d26f0bd0b3a184f194e5bec061c,m,24.5174,Germany,96.0,24.5174,m
20,20,c37faca0c57b00494e651ecde3904de9fa90ad1f,m,24.5174,Sweden,14.0,24.5174,m
21,21,839c2151683c88bd98ad1ab722c4132a8e716768,f,28.0000,United States,449.0,28.0000,f
22,22,359ab576844541274a6a9c25de6c5d2c3afc8276,m,39.0000,United States,100.5,39.0000,m
23,23,84cc3f058c77d8c7e1ae84c283933f53af3eb180,m,19.0000,Portugal,71.0,19.0000,m
24,24,e7dde2f288c7b2fe346f9636cfc8fc34f0872aee,m,24.0000,Costa Rica,253.0,24.0000,m
25,25,ac9db65cd3c8c7fe5706e0f66e1fa059a0561ea5,m,26.0000,Hungary,139.5,26.0000,m
26,26,a86fd27367de6b0d941dee935ed6b4b372a4cd45,f,19.0000,Netherlands,131.0,19.0000,f
27,27,4b49cf73e79ee322cb89dd4fb728d4b279fa4a23,m,19.0000,Belgium,45.0,19.0000,m
28,28,183d198ef2792f574424cc6f3f9d09bced452d51,m,21.0000,United States,116.5,21.0000,m
29,29,1b4ef9617afd392118725e262b382dd48c492b1d,m,21.0000,United Kingdom,96.0,21.0000,m
...,...,...,...,...,...,...,...,...
233256,233256,9763fda96d905176c4aef9f8ba5549f2938ff97e,m,29.0000,Portugal,72.5,29.0000,m
233257,233257,2a7a65fc6d743f81956485f43ccd4d72a5ca9324,m,21.0000,Russian Federation,82.0,21.0000,m
233258,233258,15d0c77f89cf2660d46308d412ffdabf80b43835,m,36.0000,Austria,17.5,36.0000,m
233259,233259,eb0020cb410f62cfef052cd1951dbd680f359e40,m,24.0000,Russian Federation,498.5,24.0000,m
233260,233260,523a97417d2ac77d4079810379aa6414bed8eb19,m,21.0000,France,54.5,21.0000,m
233261,233261,d7a1831a862edf517051ea43677a5a6298e4ae49,m,23.0000,United States,70.0,23.0000,m
233262,233262,57d74bc9ef431c86170e7cdcacc4f494f7bdef37,m,18.0000,Brazil,537.0,18.0000,m
233263,233263,db33ebd706f4745ce31b97b7f441aeb3ce0d8dee,m,29.0000,Switzerland,95.0,29.0000,m
233264,233264,a9fedc220ffeed2516e103d96012509379dbaf9d,m,24.0000,Russian Federation,201.0,24.0000,m
233265,233265,8330012ab9314d1f2a549801b98e63c6eea06161,m,23.0000,Sweden,59.0,23.0000,m
233266,233266,3444ce714ab8abda550465246c92d13676862219,m,29.0000,United States,14.0,29.0000,m
233267,233267,2ae06ef75de38d510312a1c1117815f1cc79a84a,f,16.0000,Spain,66.5,16.0000,f
233268,233268,cb3122a7fbdea01b39d04bdfd2e981d8df0b3820,m,17.0000,United Kingdom,72.0,17.0000,m
233269,233269,2a15098ad4075186809c614b521358ee853e4010,f,35.0000,Netherlands,149.0,35.0000,f
233270,233270,5963c9aed160a05607efcdae29209a90fae0f7bf,m,18.0000,United States,122.5,18.0000,m
233271,233271,9c34997e5b77219785b9c34fc7733bc4612a53c8,m,20.0000,Finland,273.0,20.0000,m
233272,233272,bcdb72cc8c5c0109eaaeed326ff6f2d8205b2283,f,18.0000,United States,14.0,18.0000,f
233273,233273,a1bca71ebc26a6374bee683d6bc6f50bda31c0cd,f,30.0000,Germany,403.0,30.0000,f
233274,233274,7574ac82d225d8c09e0fa56efb805b4cc44ca4dc,m,44.0000,United Kingdom,209.0,44.0000,m
233275,233275,5a2f3cbe64c34f3941eb18e050a9fbef33b902bb,m,NaN,Sweden,158.0,24.5174,m
233276,233276,b8916697b5fecb4de815c8a265c9e1a6ea5f5f7c,m,22.0000,Russian Federation,264.0,22.0000,m
233277,233277,8b583d8dac0c25313f1564c25b6f74693a0db2cc,m,24.0000,Sri Lanka,72.0,24.0000,m
233278,233278,7b32f67a47cb8ff53c2d0f6297b2329182828751,f,18.0000,Sweden,30.0,18.0000,f
233279,233279,7e528097def0a178be1208993c4e9963b0a26c0c,f,31.0000,United States,275.0,31.0000,f
233280,233280,99dbcbb090e46947efc47be63a7dd654466f6f00,m,26.0000,Poland,100.0,26.0000,m
233281,233281,1e0f096b96d437429f87bb69d4d9ec47846b2d9d,m,26.0000,United Kingdom,259.0,26.0000,m
233282,233282,5b35a58cb51f890507c30d086121ef66b92b35f1,f,19.0000,United States,72.5,19.0000,f
233283,233283,ebda8b6e7d5787c31bddbb4d4c08af80af2cdf3a,NaN,22.0000,United Kingdom,165.0,22.0000,f
233284,233284,bc2eaff609707b14bca23e06fb5979ccd4994af1,m,17.0000,Portugal,133.0,17.0000,m
233285,233285,118276dbaf61bc28a11bfc5abca1042de1990d83,m,21.0000,Germany,561.0,21.0000,m

In [135]:
alluser.to_csv("alluser_poisson.csv")

# test

In [136]:
df_test = pd.read_csv('test.csv.gz', compression='gzip')
df_test.head()

,Id,user,artist
0,1,306e19cce2522fa2d39ff5dfc870992100ec22d2,4ac4e32b-bd18-402e-adad-ae00e72f8d85
1,2,9450d351278df4938bdea4ed86aec940a4e927ac,1f574ab1-a46d-4586-9331-f0ded23e0411
2,3,801909d6955f59033c88595d3d7f8a6a5dcd53cc,3eb72791-6322-466b-87d3-24d74901eb2d
3,4,e3ed47445c127fbeff47fb58f6bbf2f3b4535d82,61604b45-8a91-4e33-a1b6-45d7b1fec4e5
4,5,a73f46652103f3a5f7429159310f6928f79644aa,5dfdca28-9ddc-4853-933c-8bc97d87beec

In [137]:
df_test.shape

(4154804, 3)

In [138]:
df_test = df_test.join(alluser.set_index('user'), on='user')

In [140]:
df_test.shape

(4154804, 10)

In [143]:
del df_test['plays']

In [144]:
df_test

,Id,user,artist,Unnamed: 0,sex,age,country,newage,newsex
0,1,306e19cce2522fa2d39ff5dfc870992100ec22d2,4ac4e32b-bd18-402e-adad-ae00e72f8d85,181068,f,23.0,United Kingdom,23.0000,f
1,2,9450d351278df4938bdea4ed86aec940a4e927ac,1f574ab1-a46d-4586-9331-f0ded23e0411,152570,m,24.0,United States,24.0000,m
2,3,801909d6955f59033c88595d3d7f8a6a5dcd53cc,3eb72791-6322-466b-87d3-24d74901eb2d,204496,f,30.0,Sweden,30.0000,f
3,4,e3ed47445c127fbeff47fb58f6bbf2f3b4535d82,61604b45-8a91-4e33-a1b6-45d7b1fec4e5,49062,m,26.0,Romania,26.0000,m
4,5,a73f46652103f3a5f7429159310f6928f79644aa,5dfdca28-9ddc-4853-933c-8bc97d87beec,169423,m,39.0,United States,39.0000,m
5,6,55f1c89e3a102de38a0bdfcb1fe660b028c5c0af,ef58d4c9-0d40-42ba-bfab-9186c1483edd,73514,m,21.0,United Kingdom,21.0000,m
6,7,7ad7619f38bf52de421b795f3159949422b5bbee,a3cb23fc-acd3-4ce0-8f36-1e5aa6a18432,196037,NaN,NaN,Ireland,24.5174,f
7,8,2a1ab291185cfc6fb996556481e178666e9731f9,5dfdca28-9ddc-4853-933c-8bc97d87beec,164860,f,23.0,Poland,23.0000,f
8,9,3f407fff902ab403f06668f6be3d10bb9e9a02cd,000fc734-b7e1-4a01-92d1-f544261b43f5,49494,m,22.0,Romania,22.0000,m
9,10,2eea5a2b68e6e9e0d9dd6b3c1c0e1e5840fc9ce3,84783313-2a3f-4f17-ab9a-425a5d527879,193161,f,19.0,United States,19.0000,f
10,11,68acc0c856f469445dcdf2a366cafd4912a85cfc,6e64cbfa-1a60-450e-81f4-c044c868ab24,177126,m,25.0,Turkey,25.0000,m
11,12,83aa35a83fc3d93c24623e9baa2500c369b83296,75af9d25-cf32-49c0-9192-60bd8e9784e6,77643,m,19.0,Germany,19.0000,m
12,13,0bc2f8f039fe93bbbe56732578db63741e787b2e,a9100753-f539-43cf-bcc9-579566fb512e,229975,m,NaN,Germany,24.5174,m
13,14,2b1fc60b8b014c9e9812962f59ff46110acd373b,d24c555c-318d-4fa3-bcf9-a250475cf0af,50531,m,NaN,Poland,24.5174,m
14,15,81984bca18d60ff0c19db9c6a1e7b5496032a978,42884e27-dfb8-453d-990f-2ffd90bc2d1a,198923,m,19.0,Sweden,19.0000,m
15,16,baa49744bf2a5ec1afcaa43b8752a3cd45c48e82,66fc5bf8-daa4-4241-b378-9bc9077939d2,154955,f,21.0,Romania,21.0000,f
16,17,7afcc47d4cc5ee292b75938ab0cf6eec27d086ff,0039c7ae-e1a7-4a7d-9b49-0cbc716821a6,102708,m,27.0,United States,27.0000,m
17,18,2e2b672b7e281e6073b02d534529e6b2c8aa8d8d,5bf64d94-efd9-4334-96fd-e6197b0b02b8,2837,m,27.0,Bulgaria,27.0000,m
18,19,4796c3c80258e330ca53ae15e140916ce67b881a,dfe9a7c4-8cf2-47f4-9dcb-d233c2b86ec3,192918,f,17.0,United States,17.0000,f
19,20,2f8b08122b4212302d8effb66abfd2904f624d48,d59c4cda-11d9-48db-8bfe-b557ee602aed,116605,m,29.0,Germany,29.0000,m
20,21,efa323b7243e9e09c9beb4a68073ce77ececba06,5441c29d-3602-4898-b1a1-b77fa23b8e50,146887,m,37.0,Turkey,37.0000,m
21,22,84ce5c7a982e75852ba5893651ca56063d9a69cc,c3aeb863-7b26-4388-94e8-5a240f2be21b,230442,m,2.0,Russian Federation,2.0000,m
22,23,ee2c6702bfab432f4c64996078fee8b606465773,1cc5adcd-1422-4b5c-a3cd-3ecd4f43f506,76989,m,25.0,Brazil,25.0000,m
23,24,e8c8207a04b12e1bdf3463ff04cf8d889b97db56,2645702c-97a3-45dd-b408-707362116101,108794,m,23.0,Poland,23.0000,m
24,25,f79e8026573d293c8ab579a618a58cfeaa838f2c,f181961b-20f7-459e-89de-920ef03c7ed0,218701,f,23.0,United States,23.0000,f
25,26,a3ab1d1acfc37ea74b7e598c3b1e78c8e0ce3a2d,ef954679-5ee7-4016-acef-7ac71f2fa3d8,50181,f,22.0,United States,22.0000,f
26,27,6661457a3cd14c1abfc54bdd7bd0f3b714f1fc99,22a40b75-affc-4e69-8884-266d087e4751,200606,m,21.0,Finland,21.0000,m
27,28,99707265f6faaea9d811d6cfb3290159ab121580,3cb3928a-526c-4a3d-93c5-53315fa9bde0,155767,m,NaN,United Kingdom,24.5174,m
28,29,e9d044b1a8a3443d07e7f65c054c9be8f8b90408,bc710bcf-8815-42cf-bad2-3f1d12246aeb,217176,f,16.0,United Kingdom,16.0000,f
29,30,7f0c4dc08aa5ebefcafae5762685af0fae1ae4ba,28503ab7-8bf2-4666-a7bd-2644bfc7cb1d,228391,f,31.0,Romania,31.0000,f
...,...,...,...,...,...,...,...,...,...
4154774,4154775,606f2828b55c53801304fbe28cec73506aa45364,ca891d65-d9b0-4258-89f7-e6ba29d83767,2900,m,22.0,Croatia,22.0000,m
4154775,4154776,c7ed7088306f50db9d4164cf22c3d8d6ec4bc283,e618770f-e994-41c3-856f-1eedf56b6d74,22207,m,27.0,United Kingdom,27.0000,m
4154776,4154777,d0d0be5240899b3045f7f25dcff8fab957a32134,db859a53-b7ca-4892-bcda-5ef78d2c891f,93896,m,21.0,Finland,21.0000,m
4154777,4154778,b8716bf70bf2d3e2871d2dc2a03effcccb0be2eb,e938a15c-b17e-4e7a-9f68-ff0d536cab44,169015,m,27.0,United Kingdom,27.0000,m
4154778,4154779,36f2510042fa52dcc561bfaabcb2057c17d42dab,e9aca1a3-836a-4e5e-b8d4-56d20c60af5f,126914,f,30.0,United States,30.0000,f
4154779,4154780,6e1ef79d167362cbb701afd4e58d4bd3fafa3f6b,6758601f-6d57-491e-a125-037f382a5ddd,49608,f,25.0,Australia,25.0000,f
4154780,4154781,7767ddce91c4ed220e5ff692e6ff4ae7a95fb522,31745282-b1ea-4d62-939f-226b14d68e7c,156264,NaN,NaN,United States,24.5174,f
4154781,4154782,65f13f3be295ab3f87152a508696722591bfb0cd,4bd95eea-b9f6-4d70-a36c-cfea77431553,139860,f,25.0,United Kingdom,25.0000,f
4154782,4154783,1888e96c440a7837095cc4a6701440b1bad3467e,af37c51c-0790-4a29-b995-456f98a6b8c9,207854,f,20.0,Australia,20.0000,f
4154783,4154784,713534359b5729ba1367ef09e543ad3584119ec2,78ea5ea1-3c4d-4b7e-ac5d-68900319ebe2,126977,NaN,NaN,Japan,24.5174,f
4154784,4154785,78402e42fe90d87a661e8f34a3f3d7afac733929,d8354b38-e942-4c89-ba93-29323432abc3,60033,m,23.0,Poland,23.0000,m
4154785,4154786,1cecfa3969f3f0e04039a1bbfe909359aee2c70a,cbf9738d-8f81-4a92-bc64-ede09341652d,125527,m,17.0,United States,17.0000,m
4154786,4154787,d980240c3601680b6b1f78bc68f71699016f11f4,24f1766e-9635-4d58-a4d4-9413f9f98a4c,34783,m,22.0,Italy,22.0000,m
4154787,4154788,802deb631ac45116977c68bd0f617e7ca8c09196,f1a95c6b-fb2a-41a6-bfcb-2453fee2a38c,181549,m,NaN,New Zealand,24.5174,m
4154788,4154789,93300e5d981c43a7fd88f4ee690b2f6e69f3ac97,01809552-4f87-45b0-afff-2c6f0730a3be,202230,m,NaN,United Kingdom,24.5174,m
4154789,4154790,fd8aaaffcf0bf1cf07e2ec921d2dbb7fda0b7dee,97fa7dd1-4706-4fad-b6ff-e099a37837fc,113532,m,17.0,United Kingdom,17.0000,m
4154790,4154791,384e8ce74173572cb89308ad51340d307fc02529,2386cd66-e923-4e8e-bf14-2eebe2e9b973,31883,f,21.0,Poland,21.0000,f
4154791,4154792,ac1b7e05b68daa1fdc146cd2f858c9baa6c86e38,679ec43c-bc04-4bb0-b619-2da702a214ba,174000,f,30.0,Hungary,30.0000,f
4154792,4154793,bf7bfe2ac28143908b166632afcd742953af03b6,b7ffd2af-418f-4be2-bdd1-22f8b48613da,44080,m,25.0,Poland,25.0000,m
4154793,4154794,e546f28a5c868488af6941d29da51879adb3e9d7,4bd95eea-b9f6-4d70-a36c-cfea77431553,204678,m,45.0,United States,45.0000,m
4154794,4154795,b784ab15792a32ca54d18c090f045dda5f6ba312,14387b0f-765c-4852-852f-135335790466,62741,m,20.0,United States,20.0000,m
4154795,4154796,c5619533af50fd449db1932be2f10eef3a8268fa,078a9376-3c04-4280-b7d7-b20e158f345d,207580,m,21.0,United States,21.0000,m
4154796,4154797,c193faa70ffe34d0e21ea505683d332c85238b1d,6c8b9855-ba8b-48f9-ac1d-42167f7f7b18,138307,f,29.0,Canada,29.0000,f
4154797,4154798,b75e6868fc8d7d792633aa9e4a21407789f4bd84,4cc51547-88ae-49a2-bf7e-0ef65ee7a94c,120802,NaN,22.0,Japan,22.0000,f
4154798,4154799,a6740003132704da4bbce1dc44d6f9d13cd68381,f1106b17-dcbb-45f6-b938-199ccfab50cc,47526,m,28.0,Italy,28.0000,m
4154799,4154800,1772ac04f9bbd8cc7a6d1f4293005d547b790859,ff6e677f-91dd-4986-a174-8db0474b1799,183912,f,23.0,Norway,23.0000,f
4154800,4154801,ffbf7321ace55130c4df0c5e58a7e4dcd49d6a69,10adbe5e-a2c0-4bf3-8249-2b4cbf6e6ca8,216303,m,20.0,Russian Federation,20.0000,m
4154801,4154802,f7fefb72eea0fa7976eb2fc5c0f1fe9f5d1149bd,83d8a06a-4145-444a-b4ae-49e1e986206f,180335,m,19.0,Russian Federation,19.0000,m
4154802,4154803,6af6ded3c4a0894e65aed78d48f979a0ac3ce1ae,87c5dedd-371d-4a53-9f7f-80522fb7f3cb,195453,f,22.0,Poland,22.0000,f
4154803,4154804,de29005de66c93b31a34991b0c72d9f70b9fc313,c0b2500e-0cef-4130-869d-732b23ed9df5,180056,NaN,22.0,Poland,22.0000,f

In [145]:
df_test.to_csv("df_test_predict.csv")

In [166]:
predict_result = pd.read_csv("predict_result_poisson.csv")

In [167]:
predict_result['Id'] = predict_result['Unnamed: 0']

In [168]:
predict_result['plays'] = predict_result['x']

In [169]:
del predict_result['Unnamed: 0']
del predict_result['x']

In [171]:
predict_result.to_csv("kaggle_poisson.csv")

In [158]:
np.unique(predict_result.plays.isnull())

array([False], dtype=bool)

In [170]:
predict_result

              Id       plays
0              1  131.949204
1              2  217.870996
2              3  162.128560
3              4  158.567969
4              5  216.182216
5              6  166.690710
6              7  126.880856
7              8  155.042393
8              9  158.897349
9             10  173.089961
10            11  143.076871
11            12  166.543528
12            13  166.067522
13            14  195.507140
14            15  205.774625
15            16  125.976031
16            17  217.532188
17            18  206.149531
18            19  173.269640
19            20  165.681794
20            21  142.188957
21            22  175.311228
22            23  164.920158
23            24  195.661099
24            25  172.731160
25            26  172.820791
26            27  216.616569
27            28  166.386825
28            29  132.429230
29            30  125.324203
...          ...         ...
4154774  4154775  189.213931
4154775  4154776  166.172676
4154776  4154777  216.616569
4154777  4154778  166.172676
4154778  4154779  172.105049
4154779  4154780  174.166363
4154780  4154781  172.595244
4154781  4154782  131.812374
4154782  4154783  174.618707
4154783  4154784  172.324598
4154784  4154785  195.661099
4154785  4154786  218.663603
4154786  4154787  113.204876
4154787  4154788  221.284686
4154788  4154789  166.386825
4154789  4154790  167.036962
4154790  4154791  155.203337
4154791  4154792  122.495922
4154792  4154793  195.458199
4154793  4154794  215.510375
4154794  4154795  218.323562
4154795  4154796  218.210332
4154796  4154797  178.396352
4154797  4154798  172.549790
4154798  4154799  112.853063
4154799  4154800  151.220039
4154800  4154801  173.681830
4154801  4154802  173.771953
4154802  4154803  155.122844
4154803  4154804  155.122844

[4154804 rows x 2 columns]

In [188]:
p = predict_result.plays.values

In [191]:
soln_file = 'model4.csv'
test_file = 'test.csv'
with open(test_file, 'r') as test_fh:
    test_csv = csv.reader(test_fh, delimiter=',', quotechar='"')
    next(test_csv, None)

    with open(soln_file, 'w') as soln_fh:
        soln_csv = csv.writer(soln_fh,
                              delimiter=',',
                              quotechar='"',
                              quoting=csv.QUOTE_MINIMAL)
        soln_csv.writerow(['Id', 'plays'])
        i = 0
        for row in test_csv:
            id     = row[0]
            user   = row[1]
            artist = row[2]
            soln_csv.writerow([id, p[i]])
            i+=1

In [192]:
pd.read_csv('model4.csv').head()

   Id       plays
0   1  131.949204
1   2  217.870996
2   3  162.128560
3   4  158.567969
4   5  216.182216

In [ ]:
206.62659